### ISSUE TITLE
Add manager and agent roles

### ISSUE THREAD

**Issue by roronoasins** [wazuh/qa-system-framework#59]
| dev-branch |
|-------|
| [59-add-manager-agent-roles](https://github.com/wazuh/qa-system-framework/tree/59-add-manager-agent-roles) |

## Description

As a part of #57, we need to add a folder structure to the upcoming roles and some of them. We can start with the pair of manager-agent.

We will use the roles and playbooks from `wazuh-ansible` as a reference.

**Comment by roronoasins** [comment]
I have added the manager role to the repo within `qa-system-framework/provisioning/roles/wazuh/manager` path but I had the followings errors when trying to use the handler as wazuh-ansible

```
TASK [../roles/wazuh/manager : Ensure Wazuh Manager service is started and enabled.] *************************************************************************************************************************
fatal: [manager1]: FAILED! => {"changed": false, "msg": "Unable to enable service wazuh-manager: Synchronizing state of wazuh-manager.service with SysV service script with /lib/systemd/systemd-sysv-install.\nExecuting: /lib/systemd/systemd-sysv-install enable wazuh-manager\nFailed to reload daemon: Method call timed out\nupdate-rc.d: error: no runlevel symlinks to modify, aborting!\n"}
```
> Don't know if the handler is triggered or skipped since there is no logging about handlers. Tried to manually import it but nothing happened

Tomorrow will try to fix this or even add a new handler that uses `wazuh-control` instead or another way

**Comment by roronoasins** [comment]
The first provisioning structure is like follows:

```
qa-system-framework/
|-- provisioning/
|   |-- playbooks/
|   `-- roles/
|       `-- wazuh/
|           |-- manager/
|           |   |-- defauts/
|           |   |-- handlers/
|           |   |-- meta/
|           |   `-- tasks/
|           `-- vars/
|-- src/
|   `-- ...
|-- tests/
|   `-- ...
`-- ...
```

It is possible to install the manager both via repo or custom package. Here we have both scenarios reproduced:

<details><summary>Install via custom pakcages</summary>


<details><summary>inv.yml</summary>

```yml
manager:
  hosts:
    manager1:
      ip: 172.31.6.27
      ansible_host: 172.31.6.27
      ansible_user: qa
      ansible_connection: ssh 
      wazuh_custom_packages_installation_manager_enabled: true
      wazuh_custom_packages_installation_manager_rpm_url: https://packages.wazuh.com/4.x/yum/wazuh-manager-4.4.1-1.x86_64.rpm
    manager2:
      ip: 172.31.10.218
      ansible_host: 172.31.10.218
      ansible_user: qa
      ansible_connection: ssh
      wazuh_custom_packages_installation_manager_enabled: true
      wazuh_custom_packages_installation_manager_deb_url: https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-manager/wazuh-manager_4.3.10-1_amd64.deb
  vars: {}
all:
  vars:
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
    ansible_winrm_server_cert_validation: ignore
    ansible_ssh_private_key_file: /path/to/key
```

</details>

<details><summary>Playbook run and installation check</summary>

1. Install the managers using ansible

```bash
pc@pc:~/qa-system-framework/provisioning/playbooks$ ansible-playbook -i /tmp/ wazuh-manager.yml 

PLAY [manager] ***************************************************************************************

TASK [Gathering Facts] *******************************************************************************
ok: [manager1]
ok: [manager2]

TASK [../roles/wazuh/manager : Include vars/repo_vars.yml] *******************************************
ok: [manager1]
ok: [manager2]

TASK [../roles/wazuh/manager : Include vars/repo.yml] ************************************************
ok: [manager1]
ok: [manager2]

TASK [../roles/wazuh/manager : Include vars/repo_pre-release.yml] ************************************
skipping: [manager1]
skipping: [manager2]

TASK [../roles/wazuh/manager : Include vars/repo_staging.yml] ****************************************
skipping: [manager1]
skipping: [manager2]

TASK [../roles/wazuh/manager : Include tasks based on OS] ********************************************
included: qa-system-framework/provisioning/roles/wazuh/manager/tasks/RedHat.yml for manager1
included: qa-system-framework/provisioning/roles/wazuh/manager/tasks/Debian.yml for manager2

TASK [../roles/wazuh/manager : RedHat/CentOS 5 | Install Wazuh repo] *********************************
skipping: [manager1]

TASK [../roles/wazuh/manager : RedHat/CentOS/Fedora | Install Wazuh repo] ****************************
skipping: [manager1]

TASK [../roles/wazuh/manager : CentOS/RedHat/Amazon | Install wazuh-manager] *************************
skipping: [manager1]

TASK [../roles/wazuh/manager : Install Wazuh Manager from .rpm packages | yum] ***********************
skipping: [manager1]

TASK [../roles/wazuh/manager : Install Wazuh Manager from .rpm packages | dnf] ***********************
changed: [manager1]

TASK [../roles/wazuh/manager : run the handlers after the installation] ******************************

RUNNING HANDLER [../roles/wazuh/manager : start service] *********************************************

TASK [../roles/wazuh/manager : start service] ********************************************************
ok: [manager2]

RUNNING HANDLER [../roles/wazuh/manager : start service] *********************************************
changed: [manager1]

TASK [../roles/wazuh/manager : Debian/Ubuntu | Installing Wazuh repository key (Ubuntu 14)] **********
skipping: [manager2]

TASK [../roles/wazuh/manager : Debian/Ubuntu | Installing Wazuh repository key] **********************
skipping: [manager2]

TASK [../roles/wazuh/manager : Debian/Ubuntu | Add Wazuh repositories] *******************************
skipping: [manager2]

TASK [../roles/wazuh/manager : Debian/Ubuntu | Install wazuh-manager] ********************************
skipping: [manager2]

TASK [../roles/wazuh/manager : Install Wazuh Manager from .deb packages] *****************************
changed: [manager2]

TASK [../roles/wazuh/manager : run the handlers after the installation] ******************************

TASK [../roles/wazuh/manager : Ensure Wazuh Manager service is started and enabled.] *****************
ok: [manager1]

RUNNING HANDLER [../roles/wazuh/manager : Ensure Wazuh Manager service is started and enabled.] ******
changed: [manager2]

TASK [../roles/wazuh/manager : Ensure Wazuh Manager service is started and enabled.] *****************
ok: [manager2]

PLAY RECAP *******************************************************************************************
manager1                   : ok=7    changed=2    unreachable=0    failed=0    skipped=6    rescued=0    ignored=0   
manager2                   : ok=8    changed=2    unreachable=0    failed=0    skipped=6    rescued=0    ignored=0   

pc@pc:~/qa-system-framework/provisioning/playbooks$
```

2. Check the installation 

```
root@ip-172-31-10-218:/home/qa# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.3.10"
WAZUH_REVISION="40323"
WAZUH_TYPE="server"
root@ip-172-31-10-218:/home/qa#
```

```
[root@ip-172-31-6-27 qa]# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.4.1"
WAZUH_REVISION="40406"
WAZUH_TYPE="server"
[root@ip-172-31-6-27 qa]#
```

</details>

</details>




<details><summary>Install via repo</summary>


<details><summary>inv.yml</summary>

```yml
manager:
  hosts:
    manager1:
      ip: 172.31.6.27
      ansible_host: 172.31.6.27
      ansible_user: qa
      ansible_connection: ssh
    manager2:
      ip: 172.31.10.218
      ansible_host: 172.31.10.218
      ansible_user: qa
      ansible_connection: ssh
      packages_version: 4.3.10
  vars: {}
all:
  vars:
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
    ansible_winrm_server_cert_validation: ignore
    ansible_ssh_private_key_file: /path/to/key
```

</details>

<details><summary>Playbook run and installation check</summary>

1. Install the managers using ansible

```bash
pc@pc:~/qa-system-framework/provisioning/playbooks$ ansible-playbook -i /tmp/inv.yml wazuh-manager.yml 

PLAY [manager] ***************************************************************************************

TASK [Gathering Facts] *******************************************************************************
ok: [manager1]
ok: [manager2]

TASK [../roles/wazuh/manager : Include vars/repo_vars.yml] *******************************************
ok: [manager1]
ok: [manager2]

TASK [../roles/wazuh/manager : Include vars/repo.yml] ************************************************
ok: [manager1]
ok: [manager2]

TASK [../roles/wazuh/manager : Include vars/repo_pre-release.yml] ************************************
skipping: [manager1]
skipping: [manager2]

TASK [../roles/wazuh/manager : Include vars/repo_staging.yml] ****************************************
skipping: [manager1]
skipping: [manager2]

TASK [../roles/wazuh/manager : Include tasks based on OS] ********************************************
included: qa-system-framework/provisioning/roles/wazuh/manager/tasks/RedHat.yml for manager1
included: qa-system-framework/provisioning/roles/wazuh/manager/tasks/Debian.yml for manager2

TASK [../roles/wazuh/manager : RedHat/CentOS 5 | Install Wazuh repo] *********************************
skipping: [manager1]

TASK [../roles/wazuh/manager : RedHat/CentOS/Fedora | Install Wazuh repo] ****************************
ok: [manager1]

TASK [../roles/wazuh/manager : CentOS/RedHat/Amazon | Install wazuh-manager] *************************
changed: [manager1]

TASK [../roles/wazuh/manager : Install Wazuh Manager from .rpm packages | yum] ***********************
skipping: [manager1]

TASK [../roles/wazuh/manager : Install Wazuh Manager from .rpm packages | dnf] ***********************
skipping: [manager1]

TASK [../roles/wazuh/manager : run the handlers after the installation] ******************************

RUNNING HANDLER [../roles/wazuh/manager : start service] *********************************************

TASK [../roles/wazuh/manager : start service] ********************************************************
ok: [manager2]

RUNNING HANDLER [../roles/wazuh/manager : start service] *********************************************
changed: [manager1]

TASK [../roles/wazuh/manager : Debian/Ubuntu | Installing Wazuh repository key (Ubuntu 14)] **********
skipping: [manager2]

TASK [../roles/wazuh/manager : Debian/Ubuntu | Installing Wazuh repository key] **********************
ok: [manager2]

TASK [../roles/wazuh/manager : Debian/Ubuntu | Add Wazuh repositories] *******************************
ok: [manager2]

TASK [../roles/wazuh/manager : Debian/Ubuntu | Install wazuh-manager] ********************************
changed: [manager2]

TASK [../roles/wazuh/manager : Install Wazuh Manager from .deb packages] *****************************
skipping: [manager2]

TASK [../roles/wazuh/manager : run the handlers after the installation] ******************************

TASK [../roles/wazuh/manager : Ensure Wazuh Manager service is started and enabled.] *****************
ok: [manager1]

RUNNING HANDLER [../roles/wazuh/manager : Ensure Wazuh Manager service is started and enabled.] ******
changed: [manager2]

TASK [../roles/wazuh/manager : Ensure Wazuh Manager service is started and enabled.] *****************
ok: [manager2]

PLAY RECAP *******************************************************************************************
manager1                   : ok=8    changed=2    unreachable=0    failed=0    skipped=5    rescued=0    ignored=0   
manager2                   : ok=10   changed=2    unreachable=0    failed=0    skipped=4    rescued=0    ignored=0   

pc@pc:~/qa-system-framework/provisioning/playbooks$
```

2. Check the installation 

```
root@ip-172-31-10-218:/home/qa# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.3.10"
WAZUH_REVISION="40323"
WAZUH_TYPE="server"
root@ip-172-31-10-218:/home/qa#
```

> You can change the version installed when using `packages_version` within the inventory

```
[root@ip-172-31-6-27 qa]# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.4.4"
WAZUH_REVISION="40411"
WAZUH_TYPE="server"
[root@ip-172-31-6-27 qa]#
```

</details>

</details>

**Comment by roronoasins** [comment]
Many OS support is getting added to the agents' provisioning. 

Currently it's working for Debian and RedHat. Besides, it is being added the rest of Deployer's supported OS, like Windows, Solaris, MacOS, etc.

**Comment by roronoasins** [comment]
The following OS are currently working:
- CentOS
- Ubuntu
- Debian
- ALAS
- RedHat
- Windows

Has been added support for both ECS and EC2 instances. Also, we can use a var to define the version that we want install via repo. For MacOS it freezes during the installation task

And these issues were reported during the research/dev:
- https://github.com/wazuh/wazuh-jenkins/issues/5309
- https://github.com/wazuh/wazuh-jenkins/issues/5310

> It is required to discuss if we want just to install the components or also check that everything is correct after the service starts

**Comment by roronoasins** [comment]
I've been working on adding the `become` to the playbook instead of having it in each task that is required in linux systems. I could not make this work.

> This is required since windows can't use the `become` var:
> windows da error por usar become cuando no se usa en su item sino en el anterior
>   fatal: [winagent1]: FAILED! => {"msg": "The powershell shell family is incompatible with the sudo become plugin"}

To achieve that I tried these workarounds:

1. Set the become var using bools/conditionals
  
    - `become: "{{ ansible_os_family != 'Windows' }}"`

    - `become: "{{ (true if (ansible_facts['os_family'] != 'Windows'))|default(false)|bool }}"`

2. Use tasks to set the become var for each role
    ```yaml
    tasks:
      - name: set become
        set_fact:
          become: "{{ (true if (ansible_facts['os_family'] != 'Windows')) or (false if (ansible_facts['os_family'] == 'Windows')) }}"

      - name: show become value
        debug:
          msg: "become value: {{ become }}"
    ```

3. Split the roles in two
    ```yaml
    - hosts: all
      roles:
        - role: ../roles/wazuh/agent
          hosts: winagent
          when: "'winagent' in group_names"
        - role: ../roles/wazuh/agent
          become: true
          hosts: agent
          when: "'agent' in group_names"
    ```

    > the vars are inherited from the first role item

So we'll maintain the individual becomes within the tasks that require them.

Also, there is a thing about MacOS instances. Don't know if it is a coincidence but the pkg installation won't end if it is run for a second time

```
TASK [../roles/wazuh/agent : Install MacOS agent from pkg | custom macos pkg] ********************************************************************************************************************************

```

Solaris and MacOS instances are installed now correctly. Tomorrow will check that everything works as expected.
